app/fangdata/forms.py
#_*_coding:utf-8_*_

from flask_wtf import FlaskForm
from wtforms import SelectField,SubmitField,validators


class SelectForm(FlaskForm):
    selectcols = SelectField(u'',validators=[validators.Optional()], choices=[], coerce=int)
    submit = SubmitField()

app/fangdata/__init__.py
from flask import Blueprint

fang = Blueprint('fang',__name__)


from . import views

app/fangdata/views.py
#_*_coding:utf-8_*_

from flask import render_template,request
from . import fang
from .dataanalysis import areas
from .forms import SelectForm
from ..models import Ave,MaxPrice,MinPrice,SampleSize,StatTime
from datetime import datetime

@fang.route('/fangdata/',methods=['GET','POST'])
def GetFangData():
    selectForm = SelectForm()
    choices = []
    index = 0
    stattimes = StatTime.query.all()
    for col in stattimes:
        choice = (index,col.time)
        choices.append(choice)
        index+=1

    selectForm.selectcols.choices = choices
    ch = [i[1] for i in choices]
    if request.method == 'POST':
        select = selectForm.selectcols.data-1
        collection = choices[select][1]
        areasmeans, areasmaxs, areasmins, areascount,stattimeall,bjaveall,shaveall,szaveall,gzaveall,hzaveall,dgaveall,huizaveall,fsaveall,zhaveall = getValue(collection)
        # print (type(stattimeall))
        return render_template('fangdata.html',
                               choices=ch,
                               collection=collection,
                               areas=areas,
                               areasmeans=areasmeans,
                               areasmaxs=areasmaxs,
                               areasmins=areasmins,
                               areascount=areascount,
                               stattimeall=stattimeall,
                               bjaveall=bjaveall,
                               shaveall=shaveall,
                               szaveall=szaveall,
                               gzaveall=gzaveall,
                               hzaveall=hzaveall,
                               dgaveall=dgaveall,
                               huizaveall=huizaveall,
                               fsaveall=fsaveall,
                               zhaveall=zhaveall,
							   year=datetime.now().year)
    areasmeans, areasmaxs, areasmins, areascount,stattimeall,bjaveall,shaveall,szaveall,gzaveall,hzaveall,dgaveall,huizaveall,fsaveall,zhaveall = getValue(choices[0][1])
    return render_template('fangdata.html',
                           choices=ch,
                               collection=choices[0][1],
                               areas=areas,
                               areasmeans=areasmeans,
                               areasmaxs=areasmaxs,
                               areasmins=areasmins,
                               areascount=areascount,
                               stattimeall=stattimeall,
                               bjaveall=bjaveall,
                               shaveall=shaveall,
                               szaveall=szaveall,
                               gzaveall=gzaveall,
                               hzaveall=hzaveall,
                               dgaveall=dgaveall,
                               huizaveall=huizaveall,
                               fsaveall=fsaveall,
                               zhaveall=zhaveall,
							   year=datetime.now().year)

def getValue(collection):
    ave = Ave.query.filter_by(time=collection)[0]
    maxprice = MaxPrice.query.filter_by(time=collection)[0]
    minprice = MinPrice.query.filter_by(time=collection)[0]
    samplesize = SampleSize.query.filter_by(time=collection)[0]

    aveall = Ave.query.all()
    bjaveall = [ave.bjave for ave in aveall]
    shaveall = [ave.shave for ave in aveall]
    szaveall = [ave.szave for ave in aveall]
    gzaveall = [ave.gzave for ave in aveall]
    hzaveall = [ave.hzave for ave in aveall]
    dgaveall = [ave.dgave for ave in aveall]
    huizaveall = [ave.huizave for ave in aveall]
    fsaveall = [ave.fsave for ave in aveall]
    zhaveall = [ave.zhave for ave in aveall]

    stattime = StatTime.query.all()
    stattimeall = [stat.time for stat in stattime]
    #print stattimeall

    aves = []
    maxprices = []
    minprices = []
    samplesizes = []

    aves.append(ave.bjave)
    aves.append(ave.shave)
    aves.append(ave.szave)
    aves.append(ave.gzave)
    aves.append(ave.hzave)
    aves.append(ave.dgave)
    aves.append(ave.huizave)
    aves.append(ave.fsave)
    aves.append(ave.zhave)

    maxprices.append(maxprice.bjmaxprice)
    maxprices.append(maxprice.shmaxprice)
    maxprices.append(maxprice.szmaxprice)
    maxprices.append(maxprice.gzmaxprice)
    maxprices.append(maxprice.hzmaxprice)
    maxprices.append(maxprice.dgmaxprice)
    maxprices.append(maxprice.huizmaxprice)
    maxprices.append(maxprice.fsmaxprice)
    maxprices.append(maxprice.zhmaxprice)

    minprices.append(minprice.bjminprice)
    minprices.append(minprice.shminprice)
    minprices.append(minprice.szminprice)
    minprices.append(minprice.gzminprice)
    minprices.append(minprice.hzminprice)
    minprices.append(minprice.dgminprice)
    minprices.append(minprice.huizminprice)
    minprices.append(minprice.fsminprice)
    minprices.append(minprice.zhminprice)

    samplesizes.append(samplesize.bjsize)
    samplesizes.append(samplesize.shsize)
    samplesizes.append(samplesize.szsize)
    samplesizes.append(samplesize.gzsize)
    samplesizes.append(samplesize.hzsize)
    samplesizes.append(samplesize.dgsize)
    samplesizes.append(samplesize.huizsize)
    samplesizes.append(samplesize.fssize)
    samplesizes.append(samplesize.zhsize)

    return aves,maxprices,minprices,samplesizes,stattimeall,bjaveall,shaveall,szaveall,gzaveall,hzaveall,dgaveall,huizaveall,fsaveall,zhaveall

app/templates/about.html
{% extends "base.html" %}

{% block title %}关于{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static',filename='img/logo.ico') }}">
{% endblock %}

{% block content %}
    <div class="charthead"></div>
    <div class="container">
        <h3>关于网站</h3>
        <p>爬虫数据分享系统，针对不同领域数据的抓取，包括房产数据、电商数据、金融数据以及其他应用数据。并对其进行数据的处理分析呈现。</p>
        <p>本网站数据原作者如不愿意在本网站刊登内容,请及时通知本站,予以删除！</p>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
{% block head %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <script src="/static/scripts/modernizr-2.6.2.js"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename='content/bootstrap-select.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='content/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='content/site.css') }}">
    <style type="text/css">
        html {
            height: 100%;
        }

        body {
            min-height: 100%;
            margin: 0;
            padding: 0;
            position: relative;
        }

        .wrap {
            padding-bottom: 100px;
        }

        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 40px;
            line-height: 30px;
            text-align: center;
            background-color: #0F0F0F;
        }

        .charthead {
            padding: 30px;
            margin-bottom: 30px;
            font-size: 21px;
            font-weight: 200;
            line-height: 0;
            color: inherit;
        }
    </style>
{% endblock %}
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">DataShow</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <!--<form class="navbar-form navbar-right">
                    <button type="submit" class="btn btn-success">登录</button>
                </form>-->
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        {% if current_user.is_authenticated %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="">
                            {{ current_user.username }} <b class="caret"></b>
                        </a>

                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('serverinfo.Usermanage') }} " target="_Blank">后台管理</a></li>
                            <li><a href="{{ url_for('auth.logout') }}">注销</a></li>
                        </ul>
                        {% else %}
                        <a href="{{ url_for('auth.login') }}">登录</a>
                        {% endif %}
                    </li>
                    <li>
                        {% if not current_user.is_authenticated %}
                            <a href="{{url_for('auth.register')}}">注册</a>
                        {% endif %}
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.home') }}">首页</a></li>
                    <li><a href="{{ url_for('main.about') }}">关于</a></li>
                    <li><a href="{{ url_for('main.contact') }}">联系</a></li>
                </ul>

            </div>
        </div>
    </div>

    <div class="wrap">
        {% block content %}{% endblock %}
    </div>
    <div class="footer">
        <p>Copyright &copy; 2017 - {{ year }}  DataShow . 粤ICP备18013202号-1</p>
    </div>

    <script src="/static/scripts/jquery-1.10.2.js"></script>
    <script src="/static/scripts/bootstrap.js"></script>
    <script src="/static/scripts/respond.js"></script>
    {% block scripts %}{% endblock %}

</body>
</html>

app/templates/contact.html
{% extends "base.html" %}

{% block title %}联系{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static',filename='img/logo.ico') }}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="charthead"></div>
    <h3>联系我</h3>
    <address>
        <strong>QQ：</strong>2540669209 <br />
        <strong>Email：</strong>Glf9832@163.com<br />
        <strong>Github：</strong><a href="https://github.com/Glf9832/DataShow" target="_Blank">https://github.com/Glf9832/DataShow</a><br />
    </address>
</div>
{% endblock %}

app/templates/fangdata.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}房地产数据{% endblock %}

{% block head %}
    {{ super() }}
    <script src="{{ url_for('static',filename='js/highcharts.src.js') }}"></script>
    <script src="{{ url_for('static',filename='js/dark-unica.js') }}"></script>
{% endblock %}

{% block content %}
    <div class="charthead"></div>
    <div class="container">
        <h3>房地产数据</h3>
        <br />
        <div class="row" id="container3"></div>

        <form action="#add" method="POST" class="form form-horizontal">
            <div class="form-group">
                <hr>
                <div style="float:right;width: 360px">
                    <div style="float: left;width: 70px">
                        <label class="control-label" for="selectcols">选择时间：</label>
                    </div>
                    <div style="float: left;width: 200px">
                        <select class="form-control" id="selectcols" name="selectcols">
                            {% for i in choices %}
                            <option value="{{ loop.index }}"> {{ i }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div style="float: right;width: 80px">
                        <a >
                            <input class="btn btn-default" name="submit" type="submit" value="确定">
                        </a>
                    </div>
                </div>
            </div>
        </form>
        <a name="add"></a>
        <div class="row">
            <div class="col-md-4">
                <div class="row" id="container"></div>
            </div>
            <div class="col-md-4">
                <div class="row" id="container1"></div>
            </div>

            <div class="col-md-4">
                <div class="row" id="container2"></div>
            </div>
        </div>
        <script>
            var options = {
                chart:{
                    type:'column'
                },
                title:{
                    text:'{{ collection }}各地平均房价'
                },
                subtitle:{
                    text:'数据来源：http://www.fang.com/'
                },
                xAxis:{
                    categories: {{ areas|tojson }},
                    crosshair: true
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: '价格(元/平米)'
                    }
                },
                tooltip: {
                    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                    pointFormat: '<tr><td style="color:{series.color};padding:0">均价：</td>' +
                    '<td style="padding:0"><b>{point.y:.1f} 元</b></td></tr>',
                    footerFormat: '</table>',
                    shared: true,
                    useHTML: true
                },
                plotOptions: {
                    column: {
                        borderWidth: 0
                    }
                },
                series: [{
                name: '城市',
                data: {{ areasmeans }}
                }]
            };
            var chart = Highcharts.chart('container', options);

            var options1 = {
                chart:{
                    type:'column'
                },
                title:{
                    text:'{{ collection }}各地最低与最高房价对比'
                },
                subtitle:{
                    text:'数据来源：http://www.fang.com/'
                },
                xAxis:{
                    categories: {{ areas|tojson }},
                    crosshair: true
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: '价格(元/平米)'
                    }
                },
                tooltip: {
                    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                    pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}:</td>' +
                    '<td style="padding:0"><b>{point.y:.1f} 元</b></td></tr>',
                    footerFormat: '</table>',
                    shared: true,
                    useHTML: true
                },
                plotOptions: {
                    column: {
                        borderWidth: 0
                    }
                },
                series: [{
                    name: '最低价',
                    data: {{ areasmins }}
                    },{
                    name: '最高价',
                    data: {{ areasmaxs }}
                }]
            };
            var chart1 = Highcharts.chart('container1',options1);

            var options2 = {
                chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
                },
                title: {
                    text: '{{ collection }}各地楼盘统计个数'
                },
                tooltip: {
                    headerFormat: '{series.name}<br>',
                    pointFormat: '{point.name}: <b>{point.percentage:.1f}%</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                            style: {
                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                            }
                        }
                    }
                },
                series: [{
                    type: 'pie',
                    name: '统计个数',
                    data: [
                        {
                            name:'北京',
                            y:{{ areascount[0] }},
                            sliced: true,
                            selected: true
                        },
                        ['上海', {{ areascount[1] }}],
                        ['深圳', {{ areascount[2] }}],
                        ['广州', {{ areascount[3] }}],
                        ['杭州', {{ areascount[4] }}],
                        ['东莞', {{ areascount[5] }}],
                        ['惠州', {{ areascount[6] }}],
                        ['佛山', {{ areascount[7] }}],
                        ['珠海', {{ areascount[8] }}]
                    ]
                }]
            };
            var chart2 = Highcharts.chart('container2',options2);

            var options3 = {
                chart: {
                    type: 'spline'
                },
                title: {
                    text: '各地房价波动情况'
                },
                subtitle: {
                    text: '数据来源: http://www.fang.com/'
                },
                xAxis: {
                    categories: {{ stattimeall|tojson }}
                },
                yAxis: {
                    title: {
                        text: '均价 (元/平米)'
                    }
                },
                plotOptions: {
                    line: {
                        dataLabels: {
                            enabled: false          // 开启数据标签
                        },
                        enableMouseTracking: true // 关闭鼠标跟踪，对应的提示框、点击事件会失效
                    }
                },
                tooltip: {
                    headerFormat: '<b>{series.name}</b><br>',
                    pointFormat: '均价: {point.y:.2f} 元/平米'
                },
                series: [{
                    name: '北京',
                    data: {{ bjaveall }}
                }, {
                    name: '上海',
                    data: {{ shaveall }}
                }, {
                    name: '深圳',
                    data: {{ szaveall }}
                }, {
                    name: '广州',
                    data: {{ gzaveall }}
                }, {
                    name: '杭州',
                    data: {{ hzaveall }}
                }, {
                    name: '东莞',
                    data: {{ dgaveall }}
                }, {
                    name: '惠州',
                    data: {{ huizaveall }}
                }, {
                    name: '佛山',
                    data: {{ fsaveall }}
                }, {
                    name: '珠海',
                    data: {{ zhaveall }}
                }]
            };
            var chart3 = Highcharts.chart('container3',options3);
        </script>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}DataShow{% endblock %}

{% block content %}

    <div class="jumbotron">
        <div class="container">
            <h1>DataShow</h1>
            <p class="lead">DataShow是一个爬虫数据分享系统，针对不同领域数据的抓取，包括房产数据、电商数据、金融数据以及其他应用数据。并对其进行数据的处理分析呈现。</p>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2>房地产数据</h2>
                <p>
                    数据来源于房天下、链家、安居客等房产网，以全国各大一二线城市新房楼盘数据为主。
                </p>
                <p><a class="btn btn-default" href="{{ url_for('fang.GetFangData') }}">查看 &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>电商数据</h2>
                <p>暂未开放</p>
                <p><a class="btn btn-default" href="">查看 &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>金融数据</h2>
                <p>暂未开放</p>
                <p><a class="btn btn-default" href="">查看 &raquo;</a></p>
            </div>
        </div>
    </div>
{% endblock %}